title = "Benjamin Auguste"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleanalytics = "UA-163947220-1"
disqusShortname = "bauguste"

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[params]
    author = "Benjamin Auguste"
    avatarurl = "images/avatar.png"
    info = "Software Engineer and DevOps"
    description = "Benjamin Auguste's personal website and blog"
    keywords = "blog,developer,personal,java"

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 2
    url = "https://github.com/bauguste/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab"
    weight = 3
    url = "https://gitlab.com/bauguste/"
[[params.social]]
    name = "Docker"
    icon = "fab fa-docker"
    weight = 4
    url = "https://hub.docker.com/u/bauguste/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 5
    url = "https://twitter.com/_bauguste/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 1
    url = "https://www.linkedin.com/in/b-auguste/"

[languages]
  [languages.en]
        languagename = "English"
    
    [languages.fr]
        languagename = "Français"
    
    [languages.fr.params]
        info = "Software Engineer et DevOps"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
#[[menu.main]]
#    name = "About"
#    weight = 2
#    url = "/about/"